# Generated by Django 5.2.6 on 2025-10-25 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='nickname',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
