# Generated by Django 5.2.6 on 2025-10-12 02:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='diecastcollection',
            name='beginning_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
