# Generated by Django 5.2.6 on 2025-10-13 02:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_diecastcollection_beginning_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='diecastcollectionitem',
            options={'verbose_name': 'Diecast Collection Item', 'verbose_name_plural': 'Diecast Collection Items'},
        ),
        migrations.RemoveField(
            model_name='diecastcollectionitem',
            name='beginning_date',
        ),
    ]
