# Generated by Django 5.2.6 on 2025-10-13 17:02

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client', '0001_initial'),
        ('diecasts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiecastCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('beginning_date', models.DateField(default=datetime.date.today)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collections', to='client.client')),
            ],
        ),
        migrations.CreateModel(
            name='DiecastCollectionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='app_collections.diecastcollection')),
                ('diecasts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collection_items', to='diecasts.diecast')),
            ],
            options={
                'verbose_name': 'Diecast Collection Item',
                'verbose_name_plural': 'Diecast Collection Items',
                'unique_together': {('collection', 'diecasts')},
            },
        ),
    ]
