# Generated by Django 5.2.6 on 2025-10-24 17:53

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('diecasts', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DiecastCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('beginning_date', models.DateField(default=datetime.date.today)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'DiecastCollection',
            },
        ),
        migrations.CreateModel(
            name='DiecastCollectionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('condition', models.CharField(choices=[('MT', 'MINT'), ('NM', 'NEAR MINT'), ('EX', 'EXCELLENT'), ('VG', 'VERY GOOD'), ('GD', 'GOOD'), ('PR', 'POOR'), ('DMG', 'DAMEGED')], default='NM', max_length=30)),
                ('is_sealed', models.BooleanField(default=False)),
                ('purchase_price', models.DecimalField(decimal_places=2, default=10.99, max_digits=7)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='app_collections.diecastcollection')),
                ('diecasts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collection_items', to='diecasts.diecast')),
            ],
            options={
                'db_table': 'DiecastCollectionItem',
            },
        ),
    ]
