# Generated by Django 5.2.6 on 2025-10-25 17:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_collections', '0001_initial'),
        ('diecasts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diecastcollectionitem',
            name='diecasts',
        ),
        migrations.AddField(
            model_name='diecastcollection',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='diecastcollectionitem',
            name='diecast',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='collection_items', to='diecasts.diecast'),
            preserve_default=False,
        ),
    ]
