# Generated by Django 5.2.6 on 2025-10-20 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_collections', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='diecastcollectionitem',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='diecastcollectionitem',
            unique_together=set(),
        ),
    ]
