# Generated by Django 5.2.6 on 2025-10-20 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_collections', '0002_alter_diecastcollectionitem_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='diecastcollectionitem',
            name='condition',
            field=models.CharField(choices=[('MT', 'MINT'), ('NM', 'NEAR MINT'), ('EX', 'EXCELLENT'), ('VG', 'VERY GOOD'), ('GD', 'GOOD'), ('PR', 'POOR'), ('DMG', 'DAMEGED')], default='NM', max_length=30),
        ),
        migrations.AddField(
            model_name='diecastcollectionitem',
            name='is_sealed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='diecastcollectionitem',
            name='purchase_price',
            field=models.DecimalField(decimal_places=2, default=10.99, max_digits=7),
        ),
    ]
