# Generated by Django 5.2.6 on 2025-10-11 15:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car_Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='unnamed', max_length=100, null=True, unique=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Car_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='unnamed', max_length=100, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Diecast_Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='unnamed', max_length=100, null=True, unique=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Diecast_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='unnamed', max_length=100, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Diecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series', models.CharField(blank=True, max_length=100, null=True)),
                ('sub_series', models.CharField(blank=True, max_length=100, null=True)),
                ('release_year', models.IntegerField(blank=True, null=True)),
                ('base_number', models.CharField(blank=True, max_length=15, null=True)),
                ('color', models.CharField(blank=True, max_length=50, null=True)),
                ('wheel_type', models.CharField(blank=True, max_length=50, null=True)),
                ('designer', models.CharField(blank=True, max_length=100, null=True)),
                ('scale', models.CharField(blank=True, max_length=20, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('car_brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car_brand', to='app_collection.car_brand')),
                ('car_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car_model', to='app_collection.car_model')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diecast_brand', to='app_collection.diecast_brand')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diecast_name', to='app_collection.diecast_model')),
            ],
        ),
    ]
