# Generated by Django 5.2.6 on 2025-10-24 17:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='unnamed', max_length=100, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'CarBrand',
            },
        ),
        migrations.CreateModel(
            name='Carmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='unnamed', max_length=100, null=True)),
            ],
            options={
                'db_table': 'CarModel',
            },
        ),
        migrations.CreateModel(
            name='DiecastBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='unnamed', max_length=100, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'DiecastBrand',
            },
        ),
        migrations.CreateModel(
            name='DiecastModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='unnamed', max_length=100, null=True)),
            ],
            options={
                'db_table': 'DiecastModel',
            },
        ),
        migrations.CreateModel(
            name='Diecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series', models.CharField(blank=True, max_length=100, null=True)),
                ('sub_series', models.CharField(blank=True, max_length=100, null=True)),
                ('release_year', models.IntegerField(blank=True, null=True)),
                ('base_number', models.CharField(blank=True, max_length=15, null=True)),
                ('color', models.CharField(blank=True, max_length=50, null=True)),
                ('wheel_type', models.CharField(blank=True, max_length=50, null=True)),
                ('designer', models.CharField(blank=True, max_length=100, null=True)),
                ('scale', models.CharField(blank=True, max_length=20, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('car_brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car_brand', to='diecasts.carbrand')),
                ('car_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car_model', to='diecasts.carmodel')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diecast_brand', to='diecasts.diecastbrand')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diecast_name', to='diecasts.diecastmodel')),
            ],
            options={
                'db_table': 'Diecast',
            },
        ),
    ]
