# Generated by Django 5.2.6 on 2025-10-20 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diecasts', '0002_alter_diecast_model_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car_brand',
            name='name',
            field=models.CharField(blank=True, default='unnamed', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='car_model',
            name='name',
            field=models.CharField(blank=True, default='unnamed', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='diecast_brand',
            name='name',
            field=models.CharField(blank=True, default='unnamed', max_length=100, null=True),
        ),
    ]
